services:
  map:
    image: cyclosm-tile-server
    build: .
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - "8080:80"
    command: "run"

    # Enable CORS so that the tile server can be used in web applications hosted on different domains.
    environment:
      - ALLOW_CORS=enabled

volumes:
  osm-data:
    external: true
  osm-tiles: